version: "3.8"

services:
  zap:
    build: .
    image: my-zap:latest
    container_name: zap
    ports:
      - "8080:8080"
    volumes:
      - ./zap:/zap/wrk
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g
    environment:
      - ZAP_MODE=daemon
      - ZAP_PORT=8080
      - ZAP_API_KEY=changeme
